# -*- coding: utf-8 -*-
from . import hr_employee
from . import employee_goal
from . import employee_kpi
from . import performance_review
from . import promotion_request
from . import promotion_history
from . import warning_record
from . import reward_record
from . import training_course
from . import training_enrollment
from . import skill_matrix
from . import career_path
from . import dashboard_service
from . import ai_service
from . import notification_service
from . import res_config_settings
from . import employee_attendance
from . import employee_leave